# Generated by Django 4.0.4 on 2022-05-20 18:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('column_separator', models.CharField(choices=[('Comma(,)', 'Comma(,)'), ('Semicolon(;)', 'Semicolon(;)'), ('Quotes (“)', 'Quotes (“)'), ('Braces ({})', 'Braces ({})')], max_length=200, null=True)),
                ('string_charachter', models.CharField(choices=[('Double-quote(")', 'Double-quote(")'), ("Single-quote(')", "Single-quote(')")], max_length=200, null=True)),
                ('column_name', models.CharField(blank=True, max_length=200, null=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
