# Generated by Django 4.0.4 on 2022-05-23 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schema',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
