# Generated by Django 4.0.4 on 2022-05-20 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0002_schema_type_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schema',
            name='column_separator',
            field=models.CharField(choices=[('Comma(,)', 'Comma(,)'), ('Semicolon(;)', 'Semicolon(;)'), ('Quotes (“)', 'Quotes (“)'), ('Braces ({})', 'Braces ({})')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='schema',
            name='string_charachter',
            field=models.CharField(choices=[('Double-quote(")', 'Double-quote(")'), ("Single-quote(')", "Single-quote(')")], max_length=50, null=True),
        ),
    ]
