# Generated by Django 4.0.4 on 2022-05-23 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0002_alter_schema_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schema',
            name='column_separator',
            field=models.CharField(choices=[('Comma(,)', ','), ('Semicolon(;)', ';'), ('Quotes (")', '"')], max_length=20, null=True),
        ),
    ]
