# Generated by Django 4.0.4 on 2022-05-20 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0004_remove_schema_column_name_remove_schema_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schema',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
