# Generated by Django 4.0.4 on 2022-05-23 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0004_alter_schema_column_separator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schema',
            name='string_charachter',
            field=models.CharField(choices=[('"', 'Double-quote(")'), ("'", "Single-quote(')")], max_length=50, null=True),
        ),
    ]
